/**
 * @File Name          : DemoController.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 12/6/2019, 4:14:44 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    12/6/2019   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class DemoController {
    /**
     * An empty constructor for the testing
     */
    public DemoController() {}

    /**
     * Get the version of the SFDX demo app
     */
    public String getAppVersion() {
        return '1.0.0';
    }

    //Demo
    
}
